server:
    port: 8080
    error:
      include-stacktrace: never

spring:
    application:
        name: StockMicroservice
    datasource:
      url: jdbc:mysql://127.0.0.1:3333/pragma-stock
      username: root
      password: pragma

jimmer:
    dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
    show-sql: true
    pretty-sql: true
    database-validation-mode: error


